python rnn_main.py --name=rnn_combined_pretrained_pure_short --n-repeats=1 --ppn=8 --max-hosts=1 --cpp=4 --kind=slurm --wall-time=20mins --cleanup-time=1min --slack-time=1min --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=True --n-raw-features=0 --step-time-limit=5mins --error-on-timeout=False
python rnn_main.py --name=rnn_combined_pretrained_pure --n-repeats=5 --ppn=8 --max-hosts=1 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=True --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_sum_pretrained_pure --reductions=sum --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=True --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_prod_pretrained_pure --reductions=prod --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=True --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_max_pretrained_pure --reductions=max --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=True --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_min_pretrained_pure --reductions=min --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=True --n-raw-features=0 --step-time-limit=3hours

python rnn_main.py --name=rnn_combined_short --n-repeats=1 --ppn=8 --max-hosts=1 --cpp=4 --kind=slurm --wall-time=20mins --cleanup-time=1min --slack-time=1min --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=False --n-raw-features=0 --step-time-limit=5mins --error-on-timeout=False
python rnn_main.py --name=rnn_combined --n-repeats=5 --ppn=8 --max-hosts=1 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=False --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_sum --reductions=sum --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=False --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_prod --reductions=prod --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=False --n-raw-features=0 --step-time-limit=3hours
python rnn_main.py --name=rnn_max --reductions=max --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=False --n-raw-features=0 --step-time-limit=3hours

python rnn_main.py --name=rnn_min --reductions=min --n-repeats=5 --ppn=8 --max-hosts=4 --cpp=4 --kind=slurm --wall-time=6hours --cleanup-time=30mins --slack-time=30mins --pmem=3700 --gpu-set=0,1 --ignore-gpu=False --pretrain=False --n-raw-features=0 --step-time-limit=3hours
